---
- name: Install Chromium — Debian
  when: ansible_distribution == 'Debian'
  ansible.builtin.apt:
    pkg:
      - chromium
    update_cache: true
    state: latest

- name: Install Chromium — Ubuntu
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    pkg:
      - chromium-browser
    update_cache: true
    state: latest

# See https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#recommended-enable-user-namespace-cloning
- name: Enable user namespace cloning to allow running Chromium in a sandbox
  when: ansible_facts['architecture'] != 'aarch64'
  ansible.builtin.command: sysctl -w kernel.unprivileged_userns_clone=1
