---
- name: Deploy the Open Terms Archive engine and federated API
  hosts: all
  vars:
    ota_reverse_proxy_engine_path: "/collection-api"
    ota_reverse_proxy_federated_api_path: "/federation-api"
  tasks:
    - block:
      - name: Load the engine production config
        ansible.builtin.include_vars:
          name: ota_engine_app_config
          file: "{{ inventory_dir }}/{{ ota_engine_config_path | default('../config/production.json') }}"
      
      - ansible.builtin.include_role:
          name: engine

      - ansible.builtin.include_role:
          name: federated_api
      tags: always

    - block:
      - name: Add conf in NGINX sites-available
        ansible.builtin.template:
          src: nginx-conf.j2
          dest: '/etc/nginx/sites-available/ota'
          force: true
          mode: "644"

      - name: Link conf from sites-available to sites-enabled
        ansible.builtin.file:
          src: '/etc/nginx/sites-available/ota'
          dest: '/etc/nginx/sites-enabled/ota'
          state: link
          force: true
      become: true
      notify: Restart NGINX
  
  handlers:
  - name: Restart NGINX
    become: true
    ansible.builtin.service:
      name: nginx
      state: restarted
