namespace: opentermsarchive
name: deployment
version: 1.1.1
readme: README.md
authors:
  - Open Terms Archive contributors
description: >-
  This Ansible collection provides roles and playbooks to deploy and manage Open
  Terms Archive collections.
license:
  - EUPL-1.2
tags:
  - open_terms_archive
  - archive
  - terms
  - terms_and_conditions
  - tos
  - database
  - history
dependencies: {}
repository: https://github.com/OpenTermsArchive/deployment
documentation: https://docs.opentermsarchive.org/collections/create/
homepage: https://opentermsarchive.org
issues: https://github.com/OpenTermsArchive/deployment/issues
build_ignore: []
