ota_engine_declarations_directory: "{{ app_config.name }}"
ota_engine_declarations_branch: main
ota_engine_snapshots_branch: main
ota_engine_versions_branch: main
ota_engine_restart_delay: 10800000 # 3h in ms
