# -*- mode: ruby -*-
# vi: set ft=ruby :

guest_port = 80
host_port = ENV["PORT"] || 8080

Vagrant.configure("2") do |config|
  config.vm.define "opentermsarchive_deployment"
  config.vm.hostname = "vagrant"

  config.vm.box = "debian/bullseye64" # Unable to locate package mongodb-org
  config.vm.network "forwarded_port", guest: guest_port, host: host_port

  # based on https://github.com/rofrano/vagrant-docker-provider#example-vagrantfile
  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "rofrano/vagrant-provider:debian"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    docker.create_args = ["--cgroupns=host"]
  end

  # Provisioning step to install Python 3 and make it the default
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
    update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  SHELL
end
