- name: Add GitHub Bot SSH key
  ansible.builtin.copy:
    content: '{{ ota_engine_github_bot_private_key }}'
    dest: '/home/{{ ansible_user }}/.ssh/ota-github-bot-key'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: "600"

- name: Add GitHub SSH key to known_hosts
  ansible.builtin.known_hosts:
    name: github.com
    key: "{{ item }}"
    path: ~/.ssh/known_hosts
  with_items: # GitHub's SSH key fingerprints can be found here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
    - "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"
    - "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
    - "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
    
- name: Clone federated API repository
  ansible.builtin.git:
    repo: '{{ ota_federated_api_repo }}'
    dest: '/home/{{ ansible_user }}/{{ ota_federated_api_directory }}'
    version: '{{ ota_federated_api_branch }}'
    force: true
    key_file: '/home/{{ ansible_user }}/.ssh/ota-github-bot-key'
    depth: 1

- name: Read the production config
  shell: cat '/home/{{ ansible_user }}/{{ ota_federated_api_directory }}/config/production.json'
  register: read_config
      
- name: Save production config data into a variable
  set_fact: 
    app_config: "{{ read_config.stdout | from_json }}"

- name: Install dependencies
  ansible.builtin.command:
    cmd: npm install ci
    chdir: '/home/{{ ansible_user }}/{{ ota_federated_api_directory }}'

- name: Add .env file
  ansible.builtin.template:
    src: .env
    dest: '/home/{{ ansible_user }}/{{ ota_federated_api_directory }}/.env'
    force: true
    mode: "644"

- name: Add pm2 config file
  ansible.builtin.copy:
    src: pm2.config.cjs
    dest: '/home/{{ ansible_user }}/{{ ota_federated_api_directory }}/pm2.config.cjs'
    mode: "644"

- name: Stop federated API
  ansible.builtin.command:
    cmd: pm2 stop pm2.config.cjs
    chdir: '/home/{{ ansible_user }}/{{ ota_federated_api_directory }}'
  tags:
    - stop

- name: Add conf in NGINX sites-available
  become: true
  ansible.builtin.template:
    src: nginx-conf.j2
    dest: '/etc/nginx/sites-available/ota-federated-api'
    force: true
    mode: "644"
  notify: Restart NGINX

- name: Link conf from sites-available to sites-enabled
  become: true
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/ota-federated-api'
    dest: '/etc/nginx/sites-enabled/ota-federated-api'
    state: link
    force: true
  notify: Restart NGINX

- name: Start federated API
  ansible.builtin.command:
    cmd: pm2 startOrRestart pm2.config.cjs
    chdir: '/home/{{ ansible_user }}/{{ ota_federated_api_directory }}'
  environment:
    NODE_ENV: production
  tags:
    - restart
    - start
