---
- name: Install NGINX package
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: latest

- name: Clean default NGINX site
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify: Restart NGINX

- name: Setup NGINX conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/ota.conf
    owner: root
    group: root
    mode: "644"
  notify: Restart NGINX

- name: Add engine API conf in NGINX sites-available
  ansible.builtin.template:
    src: proxy.j2
    dest: /etc/nginx/sites-available/engine-api
    force: true
    mode: "644"
  notify: Restart NGINX

- name: Link engine API conf from sites-available to sites-enabled
  ansible.builtin.file:
    src: /etc/nginx/sites-available/engine-api
    dest: /etc/nginx/sites-enabled/engine-api
    state: link
    force: true
  notify: Restart NGINX
