---
- name: Add global git config
  ansible.builtin.copy:
    src: .gitconfig
    dest: '/home/{{ ansible_user }}/.gitconfig'
    mode: "644"

- name: Add OTA-Bot SSH key
  ansible.builtin.copy:
    content: '{{ ota_engine_ota_bot_private_key }}'
    dest: '/home/{{ ansible_user }}/.ssh/ota-bot-key'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: "600"

- name: Configure SSH to use OTA-bot account on github.com
  ansible.builtin.template:
    src: ssh_config.j2
    dest: '/home/{{ ansible_user }}/.ssh/config'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: "644"
