---
- name: Set up infrastructure
  hosts: all
  become: true

  tasks:
    - name: Load OTA engine config
      ansible.builtin.include_vars:
        name: app_config
        file: "{{ inventory_dir }}/{{ ota_config_path | default('../config/production.json') }}"
      tags: always

    - ansible.builtin.include_role:
        name: infrastructure/nginx
      vars:
        host: '{{ inventory_hostname }}'
        port: '{{ app_config.port }}'

  roles:
    - role: infrastructure/git
    - role: infrastructure/node
