name: Changelog

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    uses: OpenTermsArchive/shared-workflows/.github/workflows/changelog.yml@72065aa0a4fb63ef824928409da14caf989c9d22 # pending v0.3.0
