name: Check changelog

on:
  push:
    branches-ignore:
      - main
      - push-action/** # Temporary branches created by CasperWA/push-protected@v2 action on release workflow
  pull_request:
    types: [ opened, reopened ]
  workflow_call:
    outputs:
      release_type:
        description: The release type extracted from changelog
        value: ${{ jobs.check_changelog.outputs.release_type }}

jobs:
  check_changelog:
    uses: OpenTermsArchive/engine/.github/workflows/changelog.yml@v0.37.1
