name: Changelog

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    uses: OpenTermsArchive/shared-workflows/.github/workflows/changelog.yml@56599daff47c9d22e417c076825c390de67be18e # v0.3.0
