name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  release-decision:
    uses: OpenTermsArchive/shared-workflows/.github/workflows/release-decision.yml@72065aa0a4fb63ef824928409da14caf989c9d22 # pending v0.3.0

  changelog:
    needs: release-decision
    if: ${{ needs.release-decision.outputs.should-release == 'true' }}
    uses: OpenTermsArchive/shared-workflows/.github/workflows/changelog.yml@72065aa0a4fb63ef824928409da14caf989c9d22 # pending v0.3.0

  release:
    needs: changelog
    if: ${{ needs.changelog.outputs.release-type != 'no-release' }}
    uses: OpenTermsArchive/shared-workflows/.github/workflows/release.yml@72065aa0a4fb63ef824928409da14caf989c9d22 # pending v0.3.0
    with:
      npm: none
      galaxy: publish
    secrets: inherit

  clean-changelog:
    needs: changelog
    if: ${{ needs.changelog.outputs.release-type == 'no-release' }}
    uses: OpenTermsArchive/shared-workflows/.github/workflows/clean-changelog.yml@72065aa0a4fb63ef824928409da14caf989c9d22 # pending v0.3.0
    secrets: inherit
